version: '3.9'

services:
  api:
    build: 
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      # Map local port to application port
      - 5005:5005
    command: yarn dev
